### ISSUE TITLE
processRequestBody() inquiry

### ISSUE THREAD

**Issue by izaazira** [actions-security/pymodsecurity#4]
Hi,

I have inquiry regarding the processRequestBody(). What if the attack happened in the data send via the POST method?

Thank you.

**Comment by zimmerle** [comment]
Hi @izaazira,

There are multiple methods to analyze that. In fact, that depends on the content of the request body. ModSecurity is able to parse JSON, XML, and multipart bodies. Others may be processed in plain text.

**Comment by izaazira** [comment]
Noted. Try to send script in POST body using this pymodsecurity. The modsec can detect it.

Thank you 👍
