### ISSUE TITLE
Transaction return False but still display log matched with ModSec Rules

### ISSUE THREAD

**Issue by phungtruong12947** [actions-security/pymodsecurity#5]
Hi everyone, 
I have built this module using cmake and import it to my python code.
Tried with a sample request. Code show log that Warning match with rule files imported. But running transaction.intervention(intervention) still return False. Even a good or bad request still return False. Is this an issue or how can i detect which one is good or bad? Got rules from ModSecurity CRS. Python 3.5.2. Here is my code: [https://pastebin.com/asPfSP3g](url)

**Comment by zimmerle** [comment]
Hi @phungtruong12947,

A rule match does not actually mean that a disruptive action should be taken in place. A match can be used to set (manipulate) an anomaly score, for instance. The only kind of match that returns on intervention is whenever a rule contains a disruptive action.

**Comment by phungtruong12947** [comment]
Thanks to @zimmerle for your answer.
I'm understanding that if i want to check a request via an intervention, i need to re-write a rule that contains a disruptive action. It means i have to rewrite the Core Rule Set to match that request, not only match anomaly score?

**Comment by zimmerle** [comment]
Hi @phungtruong12947, not sure if I understood your question. But the owasp crs should work as is on v3. No need to rewrite anything.

**Comment by phungtruong12947** [comment]
`import sys
import pdb
from os import listdir
from os.path import isfile, join, split, realpath, splitext
path, filename = split(realpath(__file__))
sys.path.insert(0, path + '/ModSecurity.cpython-35m-x86_64-linux-gnu.so')
from ModSecurity import ModSecurity, Rules, Transaction, ModSecurityIntervention

RULE_PATH = '/home/capstone/dev/owasp-modsecurity-crs/rules/'

def process_intervention(transaction):
	'''Return None(Positive) False(Negative)'''
	intervention = ModSecurityIntervention()
	if intervention is None:
		return None
	if transaction.intervention(intervention):
		# It always return False here
		if intervention.log is not None:
			print(intervention.log)
		if not intervention.disruptive:
			return None
		if intervention.url is not None:
			print(intervention.url)
		else:
			print(intervention.status)
		return True
	return None

def load_rule_files(path):
	'''Load rules from a path'''
	rules = Rules()
	total_rules = 0
	rules.loadFromUri(join(path, 'basic.conf'))
	for f in listdir(path):
		full_path = join(path, f)
		if isfile(full_path):
			filename, file_extension = splitext(full_path)
			if file_extension == '.conf':
				rules_loaded = rules.loadFromUri(full_path)
				if rules_loaded < 0:
					print(rules.getParserError())
				else:
					total_rules += rules_loaded
	print('Loaded: ' + str(total_rules))
	return rules

def process_request(request):
	rules = load_rule_files(RULE_PATH)
	modsec = ModSecurity()
	transaction = Transaction(modsec, rules)

	transaction.processConnection('127.0.0.1', 52345, '127.0.0.1', 8080)

	transaction.processURI(request['path'], request['method'], '1.1')

	for k, v in req['headers'].items():
		transaction.addRequestHeader(k, v)
	transaction.processRequestHeaders()

	transaction.appendRequestBody(b'')
	transaction.processRequestBody()

	process_intervention(transaction)

if __name__ == '__main__':
	req = {
    	'path': '/docs/index.html?a=<script>alert(1)</script>&q=test',
    	'method': 'GET',
		'headers': {
			'ACCEPT-ENCODING': 'gzip, deflate',
			'USER-AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36',
			'ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
			'COOKIE': 'cart=18',
			'HOST': '35.201.157.47',
			'UPGRADE-INSECURE-REQUESTS': '1',
			'CONNECTION': 'keep-alive',
			'PURPOSE': 'prefetch',
			'ACCEPT-LANGUAGE': 'en-US,en;q=0.9'
		}
	}
	process_request(req)
`
@zimmerle here is the result when i run the code with ModSecurity CRS. The intervention still return False [](https://imgur.com/a/ehQbsoJ)

**Comment by phungtruong12947** [comment]
@zimmerle I run this sample code with Core Rule Set [](https://pastebin.com/ZUDLJxg7) and received this output [](https://imgur.com/utvaZxy). Even the out show that, i still cannot use intervention to get the result, always return False.

**Comment by phungtruong12947** [comment]
@zimmerle do i need to choose crs version or this can work with newest? I'm using installation guide from crs that include modsecurity.conf, crs-setup.conf and rules set .conf into python code. Is this OK ?
